name: walimurid3
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  image_picker: ^1.0.4
  image: ^4.1.3
  google_mlkit_face_detection: ^0.11.0
  google_mlkit_commons: ^0.7.1
  tflite_flutter: ^0.11.0
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  camera: ^0.10.5+2
  google_ml_kit: ^0.18.0
  lottie: ^3.1.2
  google_fonts: ^4.0.3
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  dropdown_search: ^6.0.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.4.0
  

flutter:
  uses-material-design: true

  # Menambahkan aset gambar
  assets:
    - assets/
    - assets/logopoltek.png
    - assets/mobile_face_net.tflite
    - assets/logo.png
    - assets/gambarmuka.png
    - assets/walibg.png
    - assets/biru.png
    - assets/iconhp.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/iconcuysmpn3.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/iconcuysmpn3.png"
  adaptive_icon_padding: true