name: mobile_presensi_kdtg
description: A new Flutter project.
publish_to: "none"

version: 1.0.2+3

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Icon launcher
  flutter_launcher_icons: ^0.13.1

  # UI & Icon
  cupertino_icons: ^1.0.2
  bubble_tab_indicator: ^0.1.4
  flutter_svg: ^1.1.6
  circular_profile_avatar: ^2.0.5
  page_transition: ^2.1.0

  # Maps & Location
  google_maps_flutter: ^2.5.3
  geolocator: ^10.1.0
  trust_location: ^2.0.13

  # Firebase & Notifications
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^17.1.2

  # Utilities
  change_app_package_name: ^1.1.0
  fluttertoast: ^8.0.9
  shared_preferences: ^2.0.5
  http: ^0.13.1
  image_picker: ^0.8.3+2
  date_format: ^2.0.2
  file_picker: ^6.1.1
  in_app_review: ^2.0.8
  camera: ^0.10.5+2
  platform: ^3.1.0
  intl: ^0.19.0
  fl_chart: ^0.69.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/ilustrasi/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"
  min_sdk_android: 28
  android_generate_round: true
  ios_content_mode: center
  remove_alpha_ios: true
